design navigate
012e/QuanLyNhaXach pull request #16
Opened 2024-11-20 17:21 UTC by ntkiet1912

2024-11-25 09:23 UTC, 012e requested changes

2024-11-25 09:23 UTC, 012e commented on BookstoreManagement/UI/MainWindow/MainWindowV.xaml
> +    Icon="C:\Users\pupgk\OneDrive\Máy tính\QuanLyNhaXach\BookstoreManagement\UI\MainWindow\icon_title.ico"
Sua link nay lai ne

2024-11-25 09:24 UTC, 012e commented on BookstoreManagement/BookstoreManagement.csproj
> +    <None Remove="UI\Resources\icon_title.ico" />
Xoa dong nay

2024-11-28 15:51 UTC, 012e commented on BookstoreManagement/UI/MainWindow/MainWindowV.xaml
> +    Icon="C:\Users\pupgk\OneDrive\Máy tính\QuanLyNhaXach\BookstoreManagement\UI\MainWindow\icon_title.ico"
Ne kiet

2024-11-28 15:51 UTC, ntkiet1912 commented on BookstoreManagement/UI/MainWindow/MainWindowV.xaml
> +    Icon="C:\Users\pupgk\OneDrive\Máy tính\QuanLyNhaXach\BookstoreManagement\UI\MainWindow\icon_title.ico"
oke Huy

2024-11-28 16:13 UTC, 012e approved these changes

2024-11-28 16:13 UTC, merged