update check input
012e/QuanLyNhaXach pull request #22
Opened 2024-12-22 07:52 UTC by ntkiet1912

2024-12-22 13:40 UTC, 012e requested changes

2024-12-22 13:40 UTC, 012e commented on BookstoreManagement/CustomerUI/CreateCustomerVM.cs
>              MessageBox.Show("Added employee successfully.", "Information", MessageBoxButton.OK, MessageBoxImage.Information);
Bug: submit fail nó vẫn show success

2024-12-22 13:40 UTC, 012e commented on BookstoreManagement/EmployeeUI/CreateEmployeeVM.cs
>              catch (Exception ex)
Bug: submit fail vẫn hiện success

2024-12-22 13:40 UTC, 012e commented on BookstoreManagement/EmployeeUI/EditEmployeeVM.cs
> +                MessageBox.Show("submit successfully");
Viết hoa chữ đâu kiệt

2024-12-22 13:40 UTC, 012e commented on BookstoreManagement/ItemUI/CreateItemVM.cs
>          MessageBox.Show("Added item successfully");
Bug: submit fail vẫn hiện success

2024-12-22 13:40 UTC, 012e commented on BookstoreManagement/TagUI/CreateTagVM.cs
>              MessageBox.Show("Added tag successfully.", "Information", MessageBoxButton.OK, MessageBoxImage.Information);
Bug: submit fail vẫn hiện success

2024-12-22 13:40 UTC, 012e commented on BookstoreManagement/TagUI/EditTagVM.cs
> +            Item = new Tag();
Dòng này làm gì vậy kiệt

2024-12-22 14:52 UTC, ntkiet1912 commented on BookstoreManagement/TagUI/EditTagVM.cs
> +            Item = new Tag();
không có dòng đó lỗi null á Huy ơi

2024-12-23 08:40 UTC, 012e approved these changes

2024-12-23 08:40 UTC, merged