add employee ui
012e/QuanLyNhaXach pull request #5
Opened 2024-11-06 09:54 UTC by ntkiet1912

2024-11-06 11:29 UTC, 012e approved these changes

2024-11-06 14:45 UTC, 012e requested changes
Còn mấy cái lặt vặt fix đi kiệt

2024-11-06 14:45 UTC, 012e commented on BookstoreManagement/UI/EmployeeUI/AllEmployeeV.xaml
> +                    <DataGridTextColumn Binding="{Binding ProfilePicture}" Header="ProfilePicture" />
Xóa cột này đi @ntkiet1912

2024-11-06 14:45 UTC, 012e commented on BookstoreManagement/UI/EmployeeUI/AllEmployeeV.xaml
> +                <DataGrid.Columns>
Chỉnh lại cho mấy cái Header chữ nó cách nhau khoảng trắng đi. vd First Name, LastName

2024-11-06 14:45 UTC, 012e commented on BookstoreManagement/UI/EmployeeUI/EditEmployeeV.xaml
> +                    <Label>FirstName</Label>
Thêm khoảng trắng vào các các label

2024-11-06 14:45 UTC, 012e commented on BookstoreManagement/UI/EmployeeUI/EditEmployeeV.xaml
> +                    <Label>Profile Picture</Label>
Cái này luôn, khi nào có ảnh thì mình thêm vào sau

2024-11-06 14:45 UTC, 012e commented on BookstoreManagement/UI/EmployeeUI/EditEmployeeV.xaml
> +                    <Label>Is Manager</Label>
Này ông để cái dấu tích đc k, đừng hiên true false

2024-11-06 17:48 UTC, ntkiet1912 commented on BookstoreManagement/UI/EmployeeUI/AllEmployeeV.xaml
> +                    <DataGridTextColumn Binding="{Binding ProfilePicture}" Header="ProfilePicture" />
thay bằng gì á huy

2024-11-06 17:56 UTC, ntkiet1912 commented on BookstoreManagement/UI/EmployeeUI/EditEmployeeV.xaml
> +                    <Label>Profile Picture</Label>
là làm gì Huy

2024-11-06 18:00 UTC, 012e commented on BookstoreManagement/UI/EmployeeUI/EditEmployeeV.xaml
> +                    <Label>Profile Picture</Label>
Xoá label với text box profile picture luôn

2024-11-09 06:09 UTC, 012e approved these changes

2024-11-09 06:18 UTC, 012e approved these changes

2024-11-09 06:18 UTC, merged